### ISSUE TITLE
ros2 urg_node parameter file

### ISSUE THREAD

**Issue by edfang1** [ros-drivers/urg_node#79]
installed sudo apt install ros-foxy-urg-node.
ros2 run urg_node getID works fine and returns ID.
ros2 run urg_node urg_node_driver __params:=/opt/ros/foxy/share/urg_node/launch/urg_node_ethernet.yaml

returns can't find serial port 115200 /dev/cu.usbmodemxxxxx

I've set the ip address in the yaml file and it just doesent seem to be reading the paramtere file anywere.  Any idea on why its not readin the parameter file and using the IP address of the hokuyo (since thats the model I have) ?

Tried to git clone and build, but colcon build comes out with a bunch of catkin (ros1) type of errors.  

Thanks for any assistance.  Apologies if this is an idiot request.  I've read everything I could find and search upon.  Thanks

urg_node_ethernet.yaml file :
```
urg_node:
  ros__parameters:
    angle_max: 3.14
    angle_min: -3.14
    ip_address: "192.168.1.68"
    ip_port: 10940
    serial_baud: 57600
    laser_frame_id: "laser"
    calibrate_time: false
    default_user_latency: 0.0
    diagnostics_tolerance: 0.05
    diagnostics_window_time: 5.0
    error_limit: 4
    get_detailed_status: false
    publish_intensity: false
    publish_multiecho: false
    cluster: 1
    skip: 0
```
